# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1b33c28d450bc333a07b4950eeddfdc2cec2ba7aa43dc7bc96f8aaca5ae434638931930c112525d61897b8b89d87949a53e7cbda00e0f9a3c0b7e91131659a7

test:
  secret_key_base: 2b2aef0c78f334636b67daa0c84c9f1301875997aff474d854d3946194c1e22ab418dd4ff113ac91ec90fdaf92aa1f9b40442fc6abb2d07e938db440071d8b74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
